---
title: "Basics of {rrrSingleCellUtils}"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Basics of rrrSingleCellUtils}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rrrSingleCellUtils)
```

## Processing a Seurat object
Run the standard processing steps in a single command
```{r eval=TRUE}
pbmc_fixed <-
    process_seurat(SeuratObject::pbmc_small,
                   run_umap_dims = 1:10,
                   resolution = 0.8)
Seurat::DimPlot(pbmc_fixed)
```

## Using SNPs to define tumor clusters
```{r eval=FALSE}
two_sobj <- qs::qread("/home/gdrobertslab/mvc002/analyses/roberts/dev/testSnps/output/patient_met_1/two_sobj.qs")

# Do cell type annotation so I can use macrophages and monocytes as known normal cells
# The idea is that Osteosarcoma cells are unlikely to be mistakenly annotated as macrophages or monocytes
hpca <- celldex::HumanPrimaryCellAtlasData()
imm_cells <- celldex::MonacoImmuneData()
blueprint <- celldex::BlueprintEncodeData()

cell_assign <-
    SingleR::SingleR(as.SingleCellExperiment(two_sobj),
                     ref = list(hpca,
                                imm_cells,
                                blueprint),
                     labels = list(hpca$label.main,
                                   imm_cells$label.main,
                                   blueprint$label.main))

two_sobj$cell_type <-
    cell_assign$labels

two_sobj$cell_score <-
    cell_assign$scores %>%
    apply(MARGIN = 1, function(x) max(x, na.rm = TRUE))

control_celltypes <- c("Monocytes", "Macrophages")

# Figure out which clusters are more than 50% control celltypes
normal_clusters <-
    match_celltype_clusters(sobject = two_sobj,
                            normal_celltypes = control_celltypes,
                            cluster_col = "used_clusters",
                            celltype_col = "cell_type")

c_b_t <-
    two_sobj@meta.data %>%
    select(used_clusters) %>%
    dplyr::rename(cell_group = used_clusters) %>%
    rownames_to_column("cell_barcode") %>%
    as_tibble() %>%
    mutate(bam_file = paste0("/home/gdrobertslab/lab/Counts/",
                             str_remove(cell_barcode, "_.*"),
                             "/outs/possorted_genome_bam.bam"),
           cell_barcode = str_remove(cell_barcode, ".+_"))

snp_tree <-
    get_snp_tree(cellid_bam_table = c_b_t,
                 ploidy = "GRCh37",
                 ref_fasta = "/home/gdrobertslab/lab/GenRef/10x-human/fasta/genome.fa",
                 min_depth = 5,
                 temp_dir = "/gpfs0/scratch/mvc002/test_two_sobj",
                 sbatch_base = "two_sobj",
                 slurm_base = "/gpfs0/scratch/mvc002/test_two_sobj/two_sobj",
                 min_sites_covered = 1000,
                 cleanup = FALSE)

png("output/figures/testTwoSobjOutput1.png",
    width = 2500,
    height = 2500,
    res = 300)
plot(snp_tree)
dev.off()

cut_n_groups <- 2

new_two_sobj <-
    label_tree_groups(sobject = two_sobj,
                      dist_tree = snp_tree,
                      group_col_name = "used_clusters",
                      normal_groups = normal_clusters,
                      cut_n_groups = cut_n_groups)

png("testTwoSobjOutput2.png",
    width = 7000,
    height = 2500,
    res = 300)
DimPlot(new_two_sobj,
        group.by = c("snp_tumor_call",
                     "cell_type"),
        label = TRUE,
        repel = TRUE) +
    NoLegend()
dev.off()
```