---
title: "multiomics_analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{multiomics_analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rrrSingleCellUtils)
```

# Multiomics data with two species, selecting human
```{r loadRawMultiBoth, eval=FALSE}
multiomics_hg19 <-
    tenx_load_qc(h5_file = "/home/gdrobertslab/lab/Counts/S0150/filtered_feature_bc_matrix.h5",
                 species_pattern = "^hg19-",
                 exp_type = "GEX+ATAC")

multiomics_hg19
```


```{r annotGenesATAC, eval=FALSE}
Seurat::DefaultAssay(multiomics_hg19) <- "ATAC"
multiomics_hg19 <-
    annotate_atac(multiomics_hg19,
                  "/home/gdrobertslab/lab/GenRef/10x-human_arc/genes/genes.gtf")

```

## Nucleosome signal
```{r nucleosome, eval=FALSE}
multiomics_hg19 <- add_nucleosome_signal(multiomics_hg19)
```

## Transcription start site enrichment
```{r tss, eval=FALSE}
multiomics_hg19 <- tss_enrichment(multiomics_hg19)
```

