#!/bin/bash
#SBATCH --job-name=R0037
#SBATCH --output=R0037-%j.out
#SBATCH --time=120:00:00
#SBATCH --cpus-per-task=20
#SBATCH --mail-user=ryan.roberts@nationwidechildrens.org
#SBATCH --mail-type=ALL
#SBATCH --array=0-3
#SBATCH --dependency=afterany:896516

## set variables
CommonFolderName="R0037"
RunName="R0037"
BCLFolderName="210527_A01088_0204_BH23MJDMXY_Roberts"

FolderRoot="/gpfs0/home2/gdrobertslab/lab/"
BCLFolder="BCLs/"
FASTQFolder="FASTQs/"
CountsFolder="Counts/"

SampleNameArray=(S0116 S0126 S0127 S0128)
SampleName=${SampleNameArray[${SLURM_ARRAY_TASK_ID}]}

GenRef="10x-DNA-human"
NumCells=1000


## set path info
export PATH=/gpfs0/home/gdrobertslab/lab/Tools/10x/cellranger-dna-1.1.0:$PATH
ml load bcl2fastq/2.20.2
cd $TMPDIR

## perform alignment and count genes
 cellranger-dna cnv \
  --id $SampleName \
  --fastqs $FolderRoot$FASTQFolder$CommonFolderName/$RunName/$SampleName/Filtered/ \
  --sample $SampleName \
  --reference $FolderRoot"GenRef/"$GenRef 

## copy the files over from the temporary directory
if test -d "$FolderRoot$CountsFolder$SampleName"
then
  mkdir $FolderRoot$CountsFolder$SampleName-$(date +'%Y%m%d')
  cp -R $TMPDIR/$SampleName/outs/* $FolderRoot$CountsFolder$SampleName-$(date +'%Y%m%d')
else
  mkdir $FolderRoot$CountsFolder$SampleName
  cp -R $TMPDIR/$SampleName/outs/* $FolderRoot$CountsFolder$SampleName
fi
