#!/bin/bash
#SBATCH --job-name=placeholder_slurm_name
#SBATCH --output=placeholder_slurm_out
#SBATCH --error=placeholder_slurm_out
#SBATCH --time=1-00:00:00
#SBATCH --cpus-per-task=30
#SBATCH --array=0-placeholder_array_max
#SBATCH --wait
placeholder_email

set -e

## set variables
CommonFolderName=placeholder_run_name

RunName=placeholder_run_name

BCLFolderNameArray=(placeholder_bcl_folder_array)
BCLFolderName=${BCLFolderNameArray[${SLURM_ARRAY_TASK_ID}]}

ExpType=placeholder_exp_type

BCLFolder=placeholder_bcl_path

FASTQFolder=placeholder_fastq_folder

echo $CommonFolderName
echo $BCLFolder
echo $ExpType

## set path info
export PATH=/gpfs0/home2/gdrobertslab/lab/Tools/10x/cellranger-7.1.0:$PATH
export PATH=/gpfs0/home2/gdrobertslab/lab/Tools/10x/cellranger-arc-2.0.2:$PATH
export PATH=/gpfs0/home2/gdrobertslab/lab/Tools/bcl2fastq/2.20/bin:$PATH

cd $TMPDIR

## demultiplex bcl and create fasta files
placeholder_cellranger_type mkfastq \
  --localcores=30 \
  --localmem=200 \
  --delete-undetermined \
  --samplesheet=placeholder_sample_sheet \
  --run=${BCLFolder}/${CommonFolderName}/${BCLFolderName}/ \placeholder_base_mask
  --output-dir $TMPDIR placeholder_filter_arg
#  --filter-dual-index \ #not sure we need this?

## copy the files over from the temporary directory
if [ ! -d ${FASTQFolder}/${CommonFolderName}${ExpType} ]
then
mkdir -p ${FASTQFolder}/${CommonFolderName}${ExpType}
fi

cp -R ${TMPDIR}/* ${FASTQFolder}/${CommonFolderName}${ExpType}/

sleep 3m