#!/bin/bash
#SBATCH --job-name=placeholder_run_name-align
#SBATCH --output=placeholder_run_name-align-%j.out
#SBATCH --time=120:00:00
#SBATCH --cpus-per-task=20
#SBATCH --array=0-placeholder_array_max


## set variables
CommonFolderName=placeholder_run_name
RunName=placeholder_run_name
SampleNameArray=(placeholder_sample_array_list)
SampleName=${SampleNameArray[${SLURM_ARRAY_TASK_ID}]}

FolderRoot="/gpfs0/home2/gdrobertslab/lab/"
BCLFolder="BCLs/"
FASTQFolder="FASTQs/"
CountsFolder="Counts/"

GenRefArray=(placeholder_reference_array_list)
GenRef=${GenRefArray[${SLURM_ARRAY_TASK_ID}]}

NumCells=(placeholder_num_cells_list)
NumCells=${NumCells[${SLURM_ARRAY_TASK_ID}]}

## set path info
export PATH=/gpfs0/home2/gdrobertslab/lab/Tools/10x/cellranger-3.0.2:$PATH
ml load bcl2fastq/2.20.2

cd $TMPDIR


## perform alignment and count genes
 cellranger count \
  --id $SampleName \
  --fastqs $FolderRoot$FASTQFolder$CommonFolderName/$RunName/ \
  --sample $SampleName \
  --transcriptome $FolderRoot"GenRef/"$GenRef \
  --expect-cells $NumCells 

## copy the files over from the temporary directory
if test -d "$FolderRoot$CountsFolder$SampleName"
then
  mkdir $FolderRoot$CountsFolder$SampleName-$(date +'%Y%m%d')
  cp -R $TMPDIR/$SampleName/outs/* $FolderRoot$CountsFolder$SampleName-$(date +'%Y%m%d')
else
  mkdir $FolderRoot$CountsFolder$SampleName
  cp -R $TMPDIR/$SampleName/outs/* $FolderRoot$CountsFolder$SampleName
fi

